export enum DIToken {
  // Database
  DATABASE = "DATABASE",

  // Repositories
  USER_REPOSITORY = "USER_REPOSITORY",
  ROLE_REPOSITORY = "ROLE_REPOSITORY",
  EMAIL_REPOSITORY = "EMAIL_REPOSITORY",
  CONVERSATION_REPOSITORY = "CONVERSATION_REPOSITORY",
  MESSAGE_REPOSITORY = "MESSAGE_REPOSITORY",

  // Services
  AUTH_SERVICE = "AUTH_SERVICE",
  USER_SERVICE = "USER_SERVICE",
  EMAIL_SERVICE = "EMAIL_SERVICE",
  CHAT_SERVICE = "CHAT_SERVICE",
  ROLE_SERVICE = "ROLE_SERVICE",
  FILE_UPLOAD_SERVICE = "FILE_UPLOAD_SERVICE",

  // Controllers
  AUTH_CONTROLLER = "AUTH_CONTROLLER",
  USER_CONTROLLER = "USER_CONTROLLER",
  EMAIL_CONTROLLER = "EMAIL_CONTROLLER",
  CHAT_CONTROLLER = "CHAT_CONTROLLER",
  ME_CONTROLLER = "ME_CONTROLLER",
  UPLOAD_CONTROLLER = "UPLOAD_CONTROLLER",

  // Utils
  LOGGER = "LOGGER",
  CONFIG = "CONFIG",

  // Websocket
  CHAT_WEBSOCKET = "CHAT_WEBSOCKET",

  // External clients
  GOOGLE_CLIENT = "GOOGLE_CLIENT",
}
